function out1 = diff_g_russell(q,rE,rM,params)
%DIFF_G_RUSSELL
%    OUT1 = DIFF_G_RUSSELL(A_E,A_M,B_E,B_M,C_E,C_M,alpha_E,alpha_M,Q1,Q2,Q3,rE1,rE2,rE3,rH_E,rH_M,rM1,rM2,rM3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Oct-2025 14:29:07

A_E = params.A_E; B_E = params.B_E; C_E = params.C_E;
rH_E = params.rH_E; alpha_E = params.alpha_E;

A_M = params.A_M; B_M = params.B_M; C_M = params.C_M;
rH_M = params.rH_M; alpha_M = params.alpha_M;
q1 = q(1); q2 = q(2); q3 = q(3);
rE1 = rE(1); rE2 = rE(2); rE3 = rE(3);
rM1 = rM(1); rM2 = rM(2); rM3 = rM(3);


t2 = A_E+1.0;
t3 = A_M+1.0;
t4 = A_E+C_E;
t5 = A_M+C_M;
t6 = -A_E;
t7 = -A_M;
t8 = 1.0./B_E;
t9 = 1.0./B_M;
t10 = C_E-1.0;
t11 = C_M-1.0;
t12 = alpha_E-1.0;
t13 = alpha_M-1.0;
t14 = -rE1;
t15 = -rE2;
t16 = -rE3;
t17 = 1.0./rH_E;
t18 = 1.0./rH_M;
t19 = -rM1;
t20 = -rM2;
t21 = -rM3;
t22 = 1.0./t4;
t23 = 1.0./t5;
t24 = q1+t14;
t25 = q2+t15;
t26 = q3+t16;
t27 = q1+t19;
t28 = q2+t20;
t29 = q3+t21;
t30 = t24.^2;
t31 = t25.^2;
t32 = t26.^2;
t33 = t27.^2;
t34 = t28.^2;
t35 = t29.^2;
t38 = t6.*t10.*t22;
t39 = t7.*t11.*t23;
t40 = log(t38);
t41 = log(t39);
t44 = t30+t31+t32;
t45 = t33+t34+t35;
t42 = conj(t40);
t43 = conj(t41);
t46 = sqrt(t44);
t47 = sqrt(t45);
t48 = 1.0./t46;
t49 = 1.0./t47;
t50 = t8.*t17.*t46;
t51 = t9.*t18.*t47;
t52 = t38.^t50;
t53 = t39.^t51;
t54 = conj(t52);
t55 = conj(t53);
t56 = A_E+t52;
t57 = A_M+t53;
t58 = A_E+t54;
t59 = A_M+t55;
t60 = 1.0./t56;
t61 = 1.0./t57;
t62 = 1.0./t58.^2;
t63 = 1.0./t59.^2;
t64 = A_E.*t2.*t60;
t65 = A_M.*t3.*t61;
t66 = t6+t64;
t67 = t7+t65;
t68 = t66.^alpha_E;
t69 = t67.^alpha_M;
t72 = t66.^t12;
t73 = t67.^t13;
t70 = conj(t68);
t71 = conj(t69);
t74 = conj(t72);
t75 = conj(t73);
out1 = [alpha_E.*t2.*t6.*t8.*t17.*t24.*t42.*t48.*t54.*t62.*t71.*t74+alpha_M.*t3.*t7.*t9.*t18.*t27.*t43.*t49.*t55.*t63.*t70.*t75,alpha_E.*t2.*t6.*t8.*t17.*t25.*t42.*t48.*t54.*t62.*t71.*t74+alpha_M.*t3.*t7.*t9.*t18.*t28.*t43.*t49.*t55.*t63.*t70.*t75,alpha_E.*t2.*t6.*t8.*t17.*t26.*t42.*t48.*t54.*t62.*t71.*t74+alpha_M.*t3.*t7.*t9.*t18.*t29.*t43.*t49.*t55.*t63.*t70.*t75];
end
